- name: mongodb
  hosts: mongodb
  become: yes
  tasks:
  - name: copy mongodb repo
    ansible.builtin.copy:
      src: mongdb.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: install mongodb
    ansible.builtin.dnf:
      name: mongodb-org
      state: present   

  - name: start and enable service
    ansible.builtin.service:
      name: mongod
      enable: yes
      state: started 

  - name: Allow remote connection
    ansible.builtin.replace:
      path: /etc/mongod.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'

  - name: restart service
    ansible.builtin.service:
      name: mongod
      state: restarted
     
         

